### ISSUE TITLE
Implementation of toString() method for serializable DB classes

### ISSUE THREAD

**Issue by Road606** [logistic-support/PerformanceManagement#27]
toString() method will be used for comparing DB objects which is mandatory for Unit tests.

**Comment by daniel-klesc** [comment]
Below is a list of classes implementing method toString():
- Area
- AreaStep
- DBDataProcess
- DBHistoryRecord
- ConditionProcessMaterial
- KPIOnTime
- KPIOnTimeInterval
- KPIOnTimeLimitCheckpoint
- KPIOnTimeLimitMatGrpWH
- KPIOnTimeLimitProc
- KPIOnTimeLimitProcVersion
- KPIOnTimeLimitSource
- KPIOnTimePallet
- KPIOnTimeResultClient
- KPIOnTimeResultPallet
- MaterialGroupWHResolver
- MSG
- Pallet
- Period
- Place
- Vendor

**Comment by Road606** [comment]
Changed to implement only mandatory classes KPIOnTimePallet and KPIOnTimeResultPallet
